### PR TITLE
Document generated methods

### LINKED ISSUE #42: warning: missing documentation for an associated function
`async_imap` crate maintained at https://github.com/async-email/async-imap/ has `#![warn(missing_docs)]` enabled. When `self_cell` is used as in https://github.com/async-email/async-imap/pull/86, CI fails with warnings like
```
warning: missing documentation for an associated function
  --> src/types/name.rs:7:1
   |
7  | / self_cell!(
8  | |     /// A name that matches a `LIST` or `LSUB` command.
9  | |     pub struct Name {
10 | |         owner: Box<ResponseData>,
...  |
16 | |     impl { Debug }
17 | | );
   | |_^
   |
note: the lint level is defined here
  --> src/lib.rs:76:9
   |
76 | #![warn(missing_docs)]
   |         ^^^^^^^^^^^^
   = note: this warning originates in the macro `self_cell` (in Nightly builds, run with -Z macro-backtrace for more info)
```

A solution could be to add docs to generated methods or at least `#[allow(missing_docs)]` attributes.

### PR DESCRIPTION
**Pull request by link2xt**
Fixes #42

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -499,10 +506,12 @@ macro_rules! self_cell {
             }
         }
 
+        /// Borrows owner.
         $Vis fn borrow_owner<'_q>(&'_q self) -> &'_q $Owner {
             unsafe { self.unsafe_self_cell.borrow_owner::<$Dependent<'_q>>() }
         }
 
+        /// Calls a given function with a dependent argument.
```
Comment (Voultapher) [inline src/lib.rs:514]: I'd prefer 'Calls given closure `func` with a shared reference to dependent.'

File: src/lib.rs [hunk 2]
```diff
@@ -515,6 +524,7 @@ macro_rules! self_cell {
             }
         }
 
+        /// Calls a given function with mutable dependent argument.
```
Comment (Voultapher) [inline src/lib.rs:527]: I'd prefer 'Calls given closure `func` with a unique reference to dependent.'

File: src/lib.rs [hunk 3]
```diff
@@ -528,6 +538,7 @@ macro_rules! self_cell {
 
         $crate::_covariant_access!($Covariance, $Vis, $Dependent);
 
+        /// Converts the structure into owner.
```
Comment (Voultapher) [inline src/lib.rs:541]: I'd prefer 'Consumes `self` and returns the the owner.'

File: src/lib.rs [hunk 4]
```diff
@@ -337,6 +337,7 @@ macro_rules! self_cell {
     }
 
     impl $(<$OwnerLifetime>)? $StructName $(<$OwnerLifetime>)? {
+        /// Creates a new structure.
```
Comment (Voultapher) [inline src/lib.rs:340]: I'd prefer: 

```
/// Constructs a new self-referential struct.
///
/// The provided `owner` will be moved into a heap allocated box.
/// Followed by construction of the dependent value, by calling
/// `dependent_builder` with a shared reference to the owner that
/// remains valid for the lifetime of the constructed struct.
```

**Review by Voultapher — CHANGES_REQUESTED** [review]
Thanks for the fix! Just some wording suggestions.
